baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'mejedi.dev'

[module]
[[module.imports]]
    path = 'github.com/jpanther/congo/v2'

[taxonomies]
  category = 'categories'
  tag = 'tags'

[markup]
  [markup.highlight]
    noClasses = false

[[menu.main]]
name = "Rss"
url = "/index.xml"
weight = 1

[[menu.main]]
name = "About"
url = "/Posts"
weight = 2
