baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'mejedi.dev'
theme =  ['hugo-geekblog']

[taxonomies]
  category = 'categories'
  tag = 'tags'

[markup]
  [markup.highlight]
    noClasses = false

[[menu.main]]
name = "Home"
url = "/"
weight = 1
